M48
; DRILL file KiCad 10.0.3 date 2026-09-07T16:49:23
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-07T16:49:23-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X27.11Y-74.4
X32.89Y-74.4
T2
X12.0Y-76.0
X20.0Y-4.0
X40.0Y-4.0
X48.0Y-76.0
M30
