M48
; DRILL file KiCad 10.0.3 date 2026-09-07T20:48:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-07T20:48:43-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X37.11Y-84.4
X42.89Y-84.4
T2
X4.0Y-4.0
X4.0Y-86.0
X76.0Y-4.0
X76.0Y-86.0
M30
